### ISSUE TITLE
how to set Level for log?

### ISSUE THREAD

**Issue by dragondjf** [dept2/CuteLogger#11]
i want message which level>Info, if level < Info, it shoudn't log to consle/file, how to do this?

**Comment by cyberbobs** [comment]
You should use AbstractAppender::setDetailsLevel method to set the minimal log level to be written to the appender. Example for the FileAppender (writing to file):
```c++
FileAppender* fileAppender = new FileAppender("app.log");
fileAppender->setDetailsLevel(Logger::Info);
logger->registerAppender(fileAppender);
```

Try building the Doxygen documentation for the library, this property is well described there.
