### ISSUE TITLE
Add README.md file

### ISSUE THREAD

**Issue by iamantony** [dept2/CuteLogger#14]
Hi! First of all, thanks for the such good project! Really useful.

In my opinion, the project lacks Readme file. I know, that user can use Doxygen to generate all documentation or read _Logger.cpp_ file. But when you open project page and are trying to understand what this all about, how to use it and what features this project have, you see only bunch of the files and brief "Logger: simple, convinient and ...". Well, not so "user-friendly" =)

Thanks!

**Comment by CrawlWu** [comment]
Maybe you can complete it and apply for **pull request**.

**Comment by iamantony** [comment]
@CrawlWu well, recently I decided to switch to [spdlog library](https://github.com/gabime/spdlog), so I guess... no 😉
