### ISSUE TITLE
how to use cutelogger?

### ISSUE THREAD

**Issue by yoer** [dept2/CuteLogger#15]
sorry, does the cutelogger has any readme?

**Comment by yoer** [comment]
ok, already know.

   FileAppender* fileAppender = new FileAppender("app.log");
   fileAppender->setDetailsLevel(Logger::Debug);
   Logger::globalInstance ()->registerAppender (fileAppender);

thank you! that's a great project.

**Comment by cyberbobs** [comment]
Well, we'll have to make README.md someday (see issue #14, you're not the first one on this) :) Try building the Doxygen-based documentation for the project though, it's quite useful and almost covers everything.

**Comment by yoer** [comment]
Wow, ok, thank you, thank you for your Great Project!
