### ISSUE TITLE
connect log string to Qt Slot ?

### ISSUE THREAD

**Issue by pospiech** [dept2/CuteLogger#28]
Hello, I want to print out all logging messages to a QListWidet. This is wrapped in a Qt Class which contains the function `void widgetMessageList::addString(QString & message)`

I would like to know if there is a method within cutelogger to connect to a slot, or use any Appender class to connect the logging string to my class.

**Comment by cyberbobs** [comment]
You need to create your own Appender, overloading either [AbstractAppender::append](http://dept2.github.io/CuteLogger/class_abstract_appender.html#ababa5d9cc6e606c86f3a9a6f1720255d) or same protected method in [AbstractStringAppender](http://dept2.github.io/CuteLogger/class_abstract_string_appender.html). In the overloaded method you can do anything with logged messages, including adding texts or items to any widgets of your choice.

Take a look at the [ConsoleAppender](https://github.com/dept2/CuteLogger/blob/master/src/ConsoleAppender.cpp) implementation for the simplest Appender example possible :)

**Comment by pospiech** [comment]
It works

`#ifndef SIGNALAPPENDER_H
#define SIGNALAPPENDER_H

#include <AbstractStringAppender.h>
#include <QObject>

class SignalAppender : public QObject, public AbstractStringAppender
{
    Q_OBJECT
public:
    explicit SignalAppender(QObject * parent = nullptr);

...
signals:
    void logMessage(QString &);

...
};

#endif // SIGNALAPPENDER_H
`

`
#include "signalappender.h"

SignalAppender::SignalAppender(QObject * parent)
    : QObject(parent),
      AbstractStringAppender(),
      m_ignoreEnvPattern(false)
{
    setFormat("[%{type:-7}] <%{function}> %{message}\n");
}
//! Sends the log record as a signal
/**
 * \sa AbstractStringAppender::format()
 */
void SignalAppender::append(const QDateTime& timeStamp, Logger::LogLevel logLevel, const char* file, int line,
                             const char* function, const QString& category, const QString& message)
{
   QString messageStr = formattedString(timeStamp, logLevel, file, line, function, category, message);
    emit logMessage(messageStr);
}

`
