### ISSUE TITLE
Disable escaping

### ISSUE THREAD

**Issue by arietto** [dept2/CuteLogger#35]
Hello! I'd like to switch off escaping in my log. Is it possible?
When I log JSON fragment via `LOG_TRACE()` to debug console, it contains ugly \\" and \n elements. 
Is the problem linked with [noquote](https://doc.qt.io/qt-5.9/qdebug.html#noquote)?

**Comment by cyberbobs** [comment]
It sure is. By default, QDebug [formats QString output](https://doc.qt.io/qt-5.9/qdebug.html#operator-lt-lt-16) enclosing it in quotes and escaping possibly unsafe characters (including the quotes, word wraps etc.). You can disable this just adding `.noquote()` to your LOG_TRACE call, which returns QDebug object just like qDebug macro does.

```cpp
LOG_TRACE().noquote() << "JSON:" << yourJsonVariable;
```

**Comment by arietto** [comment]
Thank you, sir!
